Auth0Domain = ""
AppRootUrl = "http://192.168.88.73:5010"
AuthClientId = ""
AuthClientSecret = ""
JwtSecret = ""
BindAddress = ":5010"
VarDirPath = "/var/greenhome"
MqttBrokerUri = "tcp://localhost:1883"
MqttConnClientId = "greenhome"
MqttConnUsername = ""
MqttConnPassword = ""
MongoConnUri = "localhost"
SessionStoreFile = "./sessionsecret.db"
LogDir  = "/var/logs/greenhome/"
